import type { CVData } from '@/types';
import { migrateLegacyCVData } from '@/src/utils/cvDefaults';

/** Static content for template gallery thumbnails and test fixtures (no user data). */
export function getSampleCVData(accentColor = '#2563EB'): CVData {
  const flat = {
    preferred_template_id: 'classic',
    accent_color: accentColor,
    font_family: 'Inter',
    full_name: 'Alex Morgan',
    professional_title: 'Senior Product Designer',
    email: 'alex.morgan@email.com',
    phone: '+1 415 555 0192',
    location: 'San Francisco, CA',
    linkedin_url: 'linkedin.com/in/alexmorgan',
    github_url: 'github.com/alexmorgan',
    links: [
      { id: 'pf', label: 'Portfolio', url: 'https://alexmorgan.design' },
      { id: 'orcid', label: 'ORCID', url: 'https://orcid.org/0000-0001-2345-6789' },
      { id: 'scholar', label: 'Google Scholar', url: 'https://scholar.google.com/citations?user=abc123' },
      { id: 'rg', label: 'ResearchGate', url: 'https://researchgate.net/profile/Alex-Morgan' },
    ],
    address: '123 Market Street, San Francisco, CA 94103',
    photo_url: null,
    summary:
      'Product designer with 8+ years shipping B2B SaaS. Focused on research-led UX, design systems, and cross-functional delivery.',
    section_visibility: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
      projects: true,
      publications: true,
      research: true,
      certifications: true,
      awards: true,
      volunteer: true,
      languages: true,
      interests: true,
      references: true,
      custom: true,
    },
    experience: [
      {
        id: 's1',
        company: 'Northwind Labs',
        title: 'Lead Product Designer',
        location: 'Remote',
        start_date: '2021-03',
        end_date: null,
        is_current: true,
        bullets: [
          'Owned end-to-end UX for the analytics suite used by 40k+ weekly active users.',
          'Built and maintained a Figma design system adopted across 6 product squads.',
          'Partnered with PM and engineering to reduce time-to-ship for major releases by ~25%.',
        ],
        description: null,
      },
      {
        id: 's2',
        company: 'Acme Studio',
        title: 'Product Designer',
        location: 'New York, NY',
        start_date: '2017-06',
        end_date: '2021-02',
        is_current: false,
        bullets: [
          'Led redesign of onboarding; improved activation by 18% in two quarters.',
          'Conducted usability studies and translated insights into prioritized roadmaps.',
        ],
        description: null,
      },
    ],
    education: [
      {
        id: 'e1',
        institution: 'State University',
        degree: "Master's",
        field_of_study: 'Human–Computer Interaction',
        start_date: '2015-09',
        end_date: '2017-05',
        gpa: '3.9',
        thesis: 'Adaptive Interfaces for Accessibility in Enterprise Software',
        advisor: 'Dr. Jane Chen',
        coursework: ['UX Research Methods', 'Cognitive Psychology', 'Design Systems'],
        honors: ['Dean\'s List', 'Graduate Research Fellowship'],
      },
      {
        id: 'e2',
        institution: 'State University',
        degree: "Bachelor's",
        field_of_study: 'Design',
        start_date: '2011-09',
        end_date: '2015-05',
        gpa: '3.7',
        description: null,
      },
    ],
    skills: [
      {
        id: 'sk1',
        category: 'technical',
        items: ['UX research', 'UI design', 'Design systems', 'Prototyping'],
      },
      {
        id: 'sk2',
        category: 'tools',
        items: ['Figma', 'FigJam', 'Maze', 'Notion'],
      },
    ],
    projects: [
      {
        id: 'p1',
        name: 'Design tokens toolkit',
        description: 'Open-source Figma plugin for syncing tokens with code repos.',
        tech_stack: ['TypeScript', 'Figma API'],
        links: [{ label: 'GitHub', url: 'https://github.com/example/tokens' }],
        start_date: '2023-01',
        end_date: null,
      },
    ],
    certifications: [
      {
        id: 'c1',
        name: 'Certified UX Professional',
        issuer: 'NN/g',
        issue_date: '2020-06',
        expiry_date: null,
        url: 'https://example.com/credential',
      },
    ],
    languages: [
      { id: 'l1', language: 'English', proficiency: 'native' },
      { id: 'l2', language: 'Spanish', proficiency: 'intermediate' },
      {
        id: 'l3',
        language: 'French',
        proficiency: 'conversational',
        cefr: { listening: 'B2', reading: 'B2', spoken: 'B1', writing: 'B1' },
      },
    ],
    awards: [
      {
        id: 'a1',
        title: 'Design Excellence Award',
        issuer: 'UX Design Association',
        date: '2022-11',
        description: 'Recognized for design system contribution.',
      },
    ],
    referrals: [
      {
        id: 'r1',
        name: 'Jordan Lee',
        title: 'VP Product',
        company: 'Northwind Labs',
        email: 'jordan@northwind.io',
        phone: '+1 415 555 0100',
        relationship: 'Direct manager',
      },
      {
        id: 'r2',
        name: 'Sam Patel',
        title: 'Engineering Director',
        company: 'Acme Studio',
        email: 'sam@acme.studio',
        relationship: 'Former colleague',
      },
      {
        id: 'r3',
        name: 'Dr. Jane Chen',
        title: 'Professor',
        company: 'State University',
        email: 'jchen@state.edu',
        relationship: 'Graduate advisor',
      },
    ],
    cv_extra: {
      publications: [
        {
          id: 'pub1',
          title: 'Adaptive UI Patterns for Enterprise Dashboards',
          authors: ['Morgan, A.', 'Chen, J.'],
          journal: 'Journal of HCI',
          year: '2019',
          doi: '10.1234/jhci.2019.001',
          url: 'https://example.com/paper',
          volume: '42',
          issue: '3',
          pages: '112-128',
          type: 'journal',
          status: 'published',
        },
      ],
      research: [
        {
          id: 'res1',
          title: 'Accessibility in Design Systems',
          institution: 'State University HCI Lab',
          role: 'Research Assistant',
          startDate: '2016-01',
          endDate: '2017-05',
          description: 'Studied WCAG compliance patterns in component libraries.',
          funding: 'NSF Grant #12345',
        },
      ],
      volunteer: [
        {
          id: 'v1',
          organization: 'Code for SF',
          role: 'Design Mentor',
          startDate: '2019-03',
          endDate: '2023-12',
          description: 'Mentored civic tech volunteers on UX best practices.',
        },
      ],
      interests: ['Typography', 'Trail running', 'Open source'],
      custom: [
        {
          id: 'cust1',
          title: 'Speaking',
          items: [
            {
              heading: 'Design Systems Summit 2023',
              subheading: 'Keynote speaker',
              date: '2023-09',
              description: 'Scaling design tokens across organizations.',
            },
          ],
        },
      ],
      personalExtra: {
        dateOfBirth: '1993-04-15',
        nationality: 'United States',
      },
    },
    watermark: false,
  };
  return migrateLegacyCVData(flat);
}
