// src/config/templateConfig.ts

import type { TemplateId } from '../types/cv.types';

export interface TemplateConfig {
  id: TemplateId;
  label: string;
  description: string;
  targetUsers: string;
  layout: 'single-column' | 'two-column';
  sidebarSections?: string[];
  sectionOrder: string[];
  educationFirst: boolean;
  showSkillBars: boolean;
  showPhoto: boolean;
  hideIfEmpty: string[];
  requiredSections: string[];
}

/**
 * Every key handled by `renderMainSection` in `src/templates/shared/sections.js`.
 * Each template's `sectionOrder` must include each key exactly once so saved orders merge
 * correctly and no section is permanently omitted for that layout.
 */
export const CV_TEMPLATE_SECTION_KEYS_ALL: readonly string[] = [
  'personal',
  'summary',
  'experience',
  'projects',
  'education',
  'skills',
  'publications',
  'research',
  'certifications',
  'awards',
  'volunteer',
  'languages',
  'interests',
  'references',
  'custom',
];

export const TEMPLATE_CONFIGS: Record<TemplateId, TemplateConfig> = {
  classic: {
    id: 'classic',
    label: 'Classic',
    description: 'Clean single-column, ATS-optimized',
    targetUsers: 'Corporate, Finance, Law, Government',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'awards',
      'volunteer',
      'publications',
      'research',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showPhoto: false,
    hideIfEmpty: ['publications', 'research', 'projects'],
    requiredSections: ['personal', 'summary', 'experience', 'education', 'skills'],
  },
  modern: {
    id: 'modern',
    label: 'Modern',
    description: 'Two-column with skills sidebar',
    targetUsers: 'Tech, Product, Marketing, Startups',
    layout: 'two-column',
    sidebarSections: ['skills', 'languages', 'certifications', 'interests'],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'publications',
      'research',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'certifications',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  academic: {
    id: 'academic',
    label: 'Academic',
    description: 'Dense, publications-first for researchers',
    targetUsers: 'PhD, Professors, Researchers, Postdocs',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'research',
      'publications',
      'education',
      'experience',
      'projects',
      'awards',
      'skills',
      'certifications',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showPhoto: false,
    hideIfEmpty: ['projects', 'volunteer'],
    requiredSections: ['personal', 'education', 'publications', 'research'],
  },
  technical: {
    id: 'technical',
    label: 'Technical',
    description: 'Skills matrix + projects focus',
    targetUsers: 'Software Engineers, DevOps, Data Scientists',
    layout: 'two-column',
    sidebarSections: ['skills', 'certifications', 'languages'],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'publications',
      'research',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'certifications',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showPhoto: false,
    hideIfEmpty: ['publications', 'research', 'volunteer'],
    requiredSections: ['personal', 'skills', 'experience', 'projects'],
  },
  minimal: {
    id: 'minimal',
    label: 'Minimal',
    description: 'Sparse executive layout',
    targetUsers: 'C-Suite, Senior Directors, VPs',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'publications',
      'research',
      'certifications',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showPhoto: false,
    hideIfEmpty: [
      'projects',
      'publications',
      'certifications',
      'volunteer',
      'research',
    ],
    requiredSections: ['personal', 'summary', 'experience'],
  },
  creative: {
    id: 'creative',
    label: 'Creative',
    description: 'Visual layout with photo support',
    targetUsers: 'Designers, Artists, Writers, UX',
    layout: 'two-column',
    sidebarSections: ['skills', 'tools', 'languages', 'interests'],
    sectionOrder: [
      'personal',
      'summary',
      'projects',
      'experience',
      'education',
      'publications',
      'research',
      'certifications',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'projects', 'skills'],
  },
  'entry-level': {
    id: 'entry-level',
    label: 'Entry Level',
    description: 'Education-first for graduates',
    targetUsers: 'Fresh Graduates, Interns, Career Changers',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'education',
      'experience',
      'projects',
      'skills',
      'certifications',
      'volunteer',
      'publications',
      'research',
      'awards',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: true,
    showSkillBars: true,
    showPhoto: false,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'education', 'skills'],
  },
  healthcare: {
    id: 'healthcare',
    label: 'Healthcare',
    description: 'Licenses, clinical experience focus',
    targetUsers: 'Doctors, Nurses, Allied Health, Therapists',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'certifications',
      'experience',
      'projects',
      'education',
      'skills',
      'awards',
      'volunteer',
      'publications',
      'research',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showPhoto: false,
    hideIfEmpty: ['projects', 'publications'],
    requiredSections: ['personal', 'certifications', 'experience', 'education'],
  },
};

/** Full catalog of unified template ids (for pickers when DB may be a subset). */
export const ALL_TEMPLATE_IDS: TemplateId[] = [
  'classic',
  'modern',
  'academic',
  'technical',
  'minimal',
  'creative',
  'entry-level',
  'healthcare',
];
