// src/config/templateConfig.ts

import type { TemplateId } from '../types/cv.types';

export interface TemplateConfig {
  id: TemplateId;
  label: string;
  description: string;
  targetUsers: string;
  /** Baked-in accent for the design picker swatch; template CSS defines the real palette. */
  templateAccent?: string;
  layout: 'single-column' | 'two-column';
  sidebarSections?: string[];
  sectionOrder: string[];
  educationFirst: boolean;
  showSkillBars: boolean;
  /** When true, the CV editor shows skill level (1–5) controls; the PDF uses bars/dots or clear level visuals. */
  showsSkillRatingInCv: boolean;
  showPhoto: boolean;
  hideIfEmpty: string[];
  requiredSections: string[];
}

/**
 * Every key handled by `renderMainSection` in `src/templates/shared/sections.js`.
 * Each template's `sectionOrder` must include each key exactly once so saved orders merge
 * correctly and no section is permanently omitted for that layout.
 */
export const CV_TEMPLATE_SECTION_KEYS_ALL: readonly string[] = [
  'personal',
  'summary',
  'experience',
  'projects',
  'education',
  'skills',
  'publications',
  'research',
  'certifications',
  'awards',
  'volunteer',
  'languages',
  'interests',
  'references',
  'custom',
];

export const TEMPLATE_CONFIGS: Record<TemplateId, TemplateConfig> = {
  classic: {
    id: 'classic',
    label: 'Classic',
    description: 'Clean single-column, ATS-optimized',
    targetUsers: 'Corporate, Finance, Law, Government',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'awards',
      'volunteer',
      'publications',
      'research',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: false,
    showPhoto: false,
    hideIfEmpty: ['publications', 'research', 'projects'],
    requiredSections: ['personal', 'summary', 'experience', 'education', 'skills'],
  },
  modern: {
    id: 'modern',
    label: 'Modern',
    description: 'Two-column with skills sidebar',
    targetUsers: 'Tech, Product, Marketing, Startups',
    layout: 'two-column',
    sidebarSections: ['skills', 'languages', 'certifications', 'interests'],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'publications',
      'research',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'certifications',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  academic: {
    id: 'academic',
    label: 'Academic',
    description: 'Dense, publications-first for researchers',
    targetUsers: 'PhD, Professors, Researchers, Postdocs',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'research',
      'publications',
      'education',
      'experience',
      'projects',
      'awards',
      'skills',
      'certifications',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: false,
    showPhoto: false,
    hideIfEmpty: ['projects', 'volunteer'],
    requiredSections: ['personal', 'education', 'publications', 'research'],
  },
  technical: {
    id: 'technical',
    label: 'Technical',
    description: 'Skills matrix + projects focus',
    targetUsers: 'Software Engineers, DevOps, Data Scientists',
    layout: 'two-column',
    sidebarSections: ['skills', 'certifications', 'languages'],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'publications',
      'research',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'certifications',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: false,
    showPhoto: false,
    hideIfEmpty: ['publications', 'research', 'volunteer'],
    requiredSections: ['personal', 'skills', 'experience', 'projects'],
  },
  minimal: {
    id: 'minimal',
    label: 'Minimal',
    description: 'Sparse executive layout',
    targetUsers: 'C-Suite, Senior Directors, VPs',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'publications',
      'research',
      'certifications',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: false,
    showPhoto: false,
    hideIfEmpty: [
      'projects',
      'publications',
      'certifications',
      'volunteer',
      'research',
    ],
    requiredSections: ['personal', 'summary', 'experience'],
  },
  creative: {
    id: 'creative',
    label: 'Creative',
    description: 'Visual layout with photo support',
    targetUsers: 'Designers, Artists, Writers, UX',
    layout: 'two-column',
    sidebarSections: ['skills', 'tools', 'languages', 'interests'],
    sectionOrder: [
      'personal',
      'summary',
      'projects',
      'experience',
      'education',
      'publications',
      'research',
      'certifications',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'projects', 'skills'],
  },
  'entry-level': {
    id: 'entry-level',
    label: 'Entry Level',
    description: 'Education-first for graduates',
    targetUsers: 'Fresh Graduates, Interns, Career Changers',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'education',
      'experience',
      'projects',
      'skills',
      'certifications',
      'volunteer',
      'publications',
      'research',
      'awards',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: true,
    showSkillBars: true,
    showsSkillRatingInCv: false,
    showPhoto: false,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'education', 'skills'],
  },
  healthcare: {
    id: 'healthcare',
    label: 'Healthcare',
    description: 'Licenses, clinical experience focus',
    targetUsers: 'Doctors, Nurses, Allied Health, Therapists',
    layout: 'single-column',
    sectionOrder: [
      'personal',
      'summary',
      'certifications',
      'experience',
      'projects',
      'education',
      'skills',
      'awards',
      'volunteer',
      'publications',
      'research',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: false,
    showPhoto: false,
    hideIfEmpty: ['projects', 'publications'],
    requiredSections: ['personal', 'certifications', 'experience', 'education'],
  },
  'amber-strike': {
    id: 'amber-strike',
    label: 'Amber Strike',
    description: 'Charcoal sidebar, amber accents, creative energy',
    targetUsers: 'Graphic designers, marketers, creative professionals',
    templateAccent: '#F5C518',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'midnight-pro': {
    id: 'midnight-pro',
    label: 'Midnight Pro',
    description: 'Deep navy sidebar, electric blue highlights',
    targetUsers: 'Software engineers, data scientists, backend developers',
    templateAccent: '#4F8EF7',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: false,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research', 'volunteer'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'golden-hour': {
    id: 'golden-hour',
    label: 'Golden Hour',
    description: 'Icon-led sections, timeline experience, golden accents',
    targetUsers: 'Creatives, UX designers, brand managers, artists',
    templateAccent: '#F0B429',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'ocean-slate': {
    id: 'ocean-slate',
    label: 'Ocean Slate',
    description: 'Ocean blue sidebar, teal chips and accents',
    targetUsers: 'Product managers, consultants, finance, operations',
    templateAccent: '#00C9A7',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'violet-edge': {
    id: 'violet-edge',
    label: 'Violet Edge',
    description: 'Inverted layout, violet header band, timeline main column',
    targetUsers: 'Marketing leads, startup founders, tech creatives, UX leads',
    templateAccent: '#A78BFA',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'modern-sidebar': {
    id: 'modern-sidebar',
    label: 'Modern Sidebar',
    description: 'Navy sidebar with skills bars — broad professional appeal',
    targetUsers: 'Product, marketing, operations, consulting, startups',
    templateAccent: '#4F8EF7',
    layout: 'two-column',
    sidebarSections: ['skills', 'languages', 'interests'],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'references',
      'custom',
      'skills',
      'languages',
      'interests',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'bold-charcoal': {
    id: 'bold-charcoal',
    label: 'Bold Charcoal',
    description: 'Charcoal sidebar, yellow accents, split-color name',
    targetUsers: 'Creative professionals, marketers, tech workers',
    templateAccent: '#F5C518',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'projects',
      'education',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: true,
    showsSkillRatingInCv: true,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
  'midnight-navy': {
    id: 'midnight-navy',
    label: 'Midnight Navy',
    description: 'Deep navy sidebar, circle-bullet skills, minimal main column',
    targetUsers: 'Software engineers, data scientists, tech professionals',
    templateAccent: '#4F8EF7',
    layout: 'two-column',
    sidebarSections: [],
    sectionOrder: [
      'personal',
      'summary',
      'experience',
      'education',
      'projects',
      'skills',
      'certifications',
      'publications',
      'research',
      'awards',
      'volunteer',
      'languages',
      'interests',
      'references',
      'custom',
    ],
    educationFirst: false,
    showSkillBars: false,
    showsSkillRatingInCv: false,
    showPhoto: true,
    hideIfEmpty: ['publications', 'research', 'volunteer'],
    requiredSections: ['personal', 'summary', 'experience', 'skills'],
  },
};

/** Full catalog of unified template ids (for pickers when DB may be a subset). */
export const ALL_TEMPLATE_IDS: TemplateId[] = [
  'classic',
  'modern',
  'academic',
  'technical',
  'minimal',
  'creative',
  'entry-level',
  'healthcare',
  'amber-strike',
  'midnight-pro',
  'midnight-navy',
  'modern-sidebar',
  'bold-charcoal',
  'golden-hour',
  'ocean-slate',
  'violet-edge',
];
